services:
  PrestaShop\Module\PsxMarketingWithGoogle\Provider\CarrierDataProvider:
    class: PrestaShop\Module\PsxMarketingWithGoogle\Provider\CarrierDataProvider
    arguments:
      - '@PrestaShop\Module\PsxMarketingWithGoogle\Adapter\ConfigurationAdapter'
      - '@PrestaShop\Module\PsxMarketingWithGoogle\Builder\CarrierBuilder'
      - '@PrestaShop\Module\PsxMarketingWithGoogle\Repository\CarrierRepository'

  PrestaShop\Module\PsxMarketingWithGoogle\Provider\GoogleTagProvider:
    class: PrestaShop\Module\PsxMarketingWithGoogle\Provider\GoogleTagProvider
